# Generated by Django 3.2.8 on 2021-10-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('product', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(max_length=5)),
                ('price_item', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
