# Generated by Django 3.2.8 on 2021-10-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=26)),
                ('product_category', models.CharField(max_length=10)),
                ('product_status', models.CharField(max_length=10)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('date_ordered', models.DateField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
